# Generated by Django 4.2.27 on 2026-01-19 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # Dependency tuples that consist of the app name, 
    # in this case blog and the migrations that must be applied before this one can be.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    # tells Django what changes to make to the database. 
    # In this case, the changes are to create a model named Post. 
    # The fields list contains exactly the same field names and types that
    #  you created in your model in models.py.
    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
