# Generated by Django 4.2.27 on 2026-01-19 10:21

from django.db import migrations, models

    # The new migrations file was created when you typed the makemigrations command. 
    # Django saw that your model had changed and that this 
    # change needed to be reflected in the database. 
    # The files are numbered sequentially, and the filename gives you an idea of what 
    # each migration does without you having to read through the file. 
    # Because each migration is numbered, you can reapply specific migrations if you wish.

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    #The operations list then carries out the changes to the database.
    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]


# makemigrations creates the migrations file locally, 
# whereas the changes are applied to the database when you run the migrate command.