# Generated by Django 4.2.27 on 2026-01-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
